import type { Env, Scope } from './types';

/**
 * THE LOAD-BEARING RULE
 *
 * Personal-layer content never reaches a third-party inference provider.
 * Not Z.ai, not Claude, not anyone. That is what makes "sovereign AI
 * companion" a technical fact rather than a marketing line.
 *
 * Enforced twice on purpose. Here, so the request fails fast without
 * burning a Core round trip. And again in Core's resolve_scope, which is
 * authoritative and which the Worker cannot override. Defence in depth,
 * because a single check is a single bug away from a leak.
 */
const CLOUD_SAFE: ReadonlySet<Scope> = new Set<Scope>(['community', 'platform']);

export function parseScope(raw: unknown): Scope {
  return raw === 'personal' || raw === 'community' ? raw : 'platform';
}

/**
 * What the endpoint being called is going to do with the request.
 *
 * `cloud_inference` — a completion is generated by an external provider.
 * `retrieval_only`  — Ground context is returned and nothing is generated
 *                     here; the device generates.
 *
 * This distinction is the whole fix for the leak described below. A gate
 * that only knows the scope cannot tell the difference between "send this
 * to Moonshot" and "hand this back for the device to answer", and so has
 * to either refuse both or permit both.
 */
export type Capability = 'cloud_inference' | 'retrieval_only';

export interface ScopeDecision {
  scope: Scope;
  destination: 'cloud' | 'mind';
}

export function decideDestination(
  scope: Scope,
  env: Env,
  capability: Capability = 'cloud_inference',
): ScopeDecision {
  if (CLOUD_SAFE.has(scope)) return { scope, destination: 'cloud' };

  // Personal scope on an endpoint that generates on Cloud. MIND_AVAILABLE
  // deliberately is NOT consulted here.
  //
  // It used to be, and that was a leak waiting on a config change: Mind
  // runs on the device, so no value of a Worker variable can make a Cloud
  // completion of a personal-scope prompt permissible. Flipping the flag
  // returned destination 'mind' and then the request carried on through
  // ground() — which embedded the user's question on Workers AI — and
  // through infer(), which sent the prompt itself to Moonshot or Alibaba,
  // because neither function ever looked at the destination. Both leaks
  // sat upstream of Core's authoritative check, which is the one place
  // designed to catch them.
  if (capability === 'cloud_inference') throw new ScopeRefusal(scope, 'cloud_inference');

  // Retrieval only. Nothing is generated at the edge and, per ground(), no
  // personal text is embedded at the edge either. Ground itself is public
  // Zimbabwean law; what needs protecting is the question, not the corpus.
  if (env.MIND_AVAILABLE === 'true') return { scope, destination: 'mind' };

  // Refuse rather than silently downgrade to platform scope. A downgrade
  // would answer confidently while withholding the user's own data, with
  // no signal that anything was missing — worse than an error.
  throw new ScopeRefusal(scope, 'retrieval_only');
}

export class ScopeRefusal extends Error {
  constructor(
    readonly scope: Scope,
    readonly capability: Capability = 'cloud_inference',
  ) {
    super('scope_requires_local_inference');
  }

  toPayload() {
    return {
      error: 'scope_requires_local_inference',
      scope: this.scope,
      message:
        this.capability === 'cloud_inference'
          ? 'Personal-layer data cannot be sent to an external inference provider. ' +
            'This endpoint generates its answer on Cloud, so it cannot serve ' +
            'personal scope at all. Retrieve context from /v1/ground/context ' +
            'and generate on the device with Shamwari Mind.'
          : 'Personal-layer data cannot be sent to an external inference provider. ' +
            'Shamwari Mind is required for this request and is not yet deployed on ' +
            'this surface.',
      capability: this.capability,
      docs: 'https://docs.shamwari.ai/scopes',
    };
  }
}
